### ISSUE TITLE
nornir_netconf???

### ISSUE THREAD

**Issue by fbing-yy** [h4ndzdatm0ld/Norconf#1]
pip install  nornir_netconf

ERROR: Could not find a version that satisfies the requirement nornir_netconf
ERROR: No matching distribution found for nornir_netconf

Where is it?
Thanks

**Comment by h4ndzdatm0ld** [comment]
There is no such package used for this repo. 

All Nornir netconf tasks come from the custom file called nc_tasks.py



Hugo Tinoco
503.347.6555
